const mongoose=require('mongoose');
const sendEmail=require('../utils/sendEmail')

const userSchema=new mongoose.Schema({
  firstName:{
    type:String,
    required:true,
    trim:true
  },
  lastName:{
    type:String,
    required:true,
    trim:true
  },
  email:{
    type:String,
    required:true,
    trim:true
  },
  password:{
    type:String,
    required:true,
    trim:true
  },
  accountType:{
    type:String,
    enum:["Admin","Student","Instructor"],
    required:true,
  },
  additionalDetal:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Profile"
  },
  courses:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Course"
  }],
  image:{
    type:String,
    required:true,
    trim:true,
  },
  courseProgress:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"CourseProgress"
  }],
  token:{
    type:String,
  },
  expireTokenTime:{
    type:Date,
  },

  cart:{
    type: mongoose.Schema.Types.ObjectId,
    ref: "Cart",
  }
})


// this is the post middleware that is triggrred when any ones new user singup
userSchema.post("save",async function (docs){
  try{
    // THis is the body for the sing up of the email Generated by chatgpt 
    const body = `
                  <div style="font-family: Arial, sans-serif; background-color: #f7f7f7; padding: 20px;">
                    <div style="max-width: 600px; margin: auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.08);">
                      <div style="padding: 30px; text-align: center;">
                        <h1 style="color: #4A90E2; margin-bottom: 10px;">🎉 Welcome to StudyNotion!</h1>
                        <p style="font-size: 16px; color: #333; margin-bottom: 20px;">
                          Hello <strong>${docs.firstName}</strong>,<br/>
                          Your account has been successfully created.
                        </p>
                        <p style="font-size: 15px; color: #555;">
                          We're excited to have you join our learning community. You can now explore courses, track progress, and grow your skills with us.
                        </p>

                        <a href="${"http://localhost:5173/login"}" style="display: inline-block; margin-top: 25px; padding: 12px 20px; background-color: #4A90E2; color: #fff; text-decoration: none; border-radius: 6px; font-weight: bold;">
                          Go to Dashboard
                        </a>

                        <hr style="margin: 40px 0; border: none; border-top: 1px solid #eee;" />

                        <p style="font-size: 13px; color: #888;">
                          If you have any questions, feel free to reply to this email. We're here to help!
                        </p>
                        <p style="font-size: 13px; color: #999; margin-top: 10px;">
                          — StudyNotion Team
                        </p>
                      </div>
                    </div>
                  </div>
                `;
    const info=await sendEmail(
      docs.email,
      "🎓 Your StudyNotion account is ready",
      body
    )
  }
  catch(err){
    // console.log("There is some error triggering the post middle ware of the singup")
    return res.status(400).json({
      success:false,
      message:"Post middleware not worked"
    })
  }
})


module.exports=mongoose.model("User",userSchema);